name: 刷步数

on:
  workflow_dispatch:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  schedule:
#    - cron: '27 0,2,4,6,8,10,12 * * *'
  watch:
    types: started

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
#    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v4
      - name: 初始化Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 开始
        run: |
          pip install requests pytz
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd}
